### ISSUE TITLE
能否将IP信息公布？

### ISSUE THREAD

**Issue by badboycxcc** [blackorbird/APT_REPORT#5]

**Comment by blackorbird** [comment]
what

**Comment by Technetium1** [comment]
**CN**
IP 地址无法在此处发布。 它们是短暂的，并且在攻击后很长时间内没有用处。 否则，如果你指的是知识产权的IP，则无需添加许可证。 请今后正确填写英文问题报告。 即使是像这条消息一样通过翻译来完成也可以。

---
**EN**
IP addresses would not be of use to publish here. They are ephemeral and not useful for very long after attacks. Otherwise, if you mean IP for intellectual property, there is no need to add a license. Please properly fill out an issue report in English in the future. It is fine even if it is done through a translator like this message.

**Comment by badboycxcc** [comment]
Yes, I need the IP information they used, if the use was brief, I also need it, if possible, add the start time in the IP
